### ISSUE TITLE
Default page output is not JSON

### ISSUE THREAD

**Issue by samtuke** [phpList/web-frontend#34]
### Short problem description
Provided headers indicate that the default message printed to browser is JSON but in fact it is not. Firefox gives error: 'SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data'

### Steps to reproduce
1. Install base-distribution
2. Navigate to e.g. http://local.server loads headers with 'Content-Type | application/json' but plain text is provided
3. Devices misunderstand the data

**Comment by oliverklee** [comment]
This most probably is a configuration issue in the rest-api package (which gets installed by the base-distribution package).

**Comment by oliverklee** [comment]
This is fixed with https://github.com/phpList/rest-api/pull/58.
